### ISSUE TITLE
Incorrect format specifier

### ISSUE THREAD

**Issue by austinliou** [pixeldustproject-p/android_hardware_qcom_audio#1]
When compiling Pixel Dust for the Pixel XL (marlin), I encounter an error in [audio_hw.c](https://github.com/pixeldustproject-p/android_hardware_qcom_audio/blob/66c4ecfa84116e12c5cb3b430208365cdfb0b2c9/hal/audio_hw.c#L3102):
`hardware/qcom/audio/hal/audio_hw.c:3102:53: error: format specifies type 'ssize_t' (aka 'int') but the argument has type 'ssize_t' (aka 'long') [-Werror,-Wformat]`

My quick fix was to change the format specifier to `%ld` instead of `%zd`, but I suspect cherry picking [this commit](https://github.com/pixeldustproject-p/android_hardware_qcom_audio/commit/3f0d3429bad5ee4729cfd87e8879ebb016b80d98) from the other branch would accomplish the same thing.

**Comment by spezi77** [comment]
Thanks for your feedback, highly appreciated. I have cherry-picked the missing commit -> p-branch should be in a better condition now. Closing this issue.
